// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package bitcoinservice

import (
	"github.com/F0rzend/simple-go-webserver/app/aggregate/bitcoin/entity"
	"sync"
)

// Ensure, that MockBTCRepository does implement BTCRepository.
// If this is not the case, regenerate this file with moq.
var _ BTCRepository = &MockBTCRepository{}

// MockBTCRepository is a mock implementation of BTCRepository.
//
// 	func TestSomethingThatUsesBTCRepository(t *testing.T) {
//
// 		// make and configure a mocked BTCRepository
// 		mockedBTCRepository := &MockBTCRepository{
// 			GetPriceFunc: func() bitcoinentity.BTCPrice {
// 				panic("mock out the GetPrice method")
// 			},
// 			SetPriceFunc: func(price bitcoinentity.BTCPrice) error {
// 				panic("mock out the SetPrice method")
// 			},
// 		}
//
// 		// use mockedBTCRepository in code that requires BTCRepository
// 		// and then make assertions.
//
// 	}
type MockBTCRepository struct {
	// GetPriceFunc mocks the GetPrice method.
	GetPriceFunc func() bitcoinentity.BTCPrice

	// SetPriceFunc mocks the SetPrice method.
	SetPriceFunc func(price bitcoinentity.BTCPrice) error

	// calls tracks calls to the methods.
	calls struct {
		// GetPrice holds details about calls to the GetPrice method.
		GetPrice []struct {
		}
		// SetPrice holds details about calls to the SetPrice method.
		SetPrice []struct {
			// Price is the price argument value.
			Price bitcoinentity.BTCPrice
		}
	}
	lockGetPrice sync.RWMutex
	lockSetPrice sync.RWMutex
}

// GetPrice calls GetPriceFunc.
func (mock *MockBTCRepository) GetPrice() bitcoinentity.BTCPrice {
	if mock.GetPriceFunc == nil {
		panic("MockBTCRepository.GetPriceFunc: method is nil but BTCRepository.GetPrice was just called")
	}
	callInfo := struct {
	}{}
	mock.lockGetPrice.Lock()
	mock.calls.GetPrice = append(mock.calls.GetPrice, callInfo)
	mock.lockGetPrice.Unlock()
	return mock.GetPriceFunc()
}

// GetPriceCalls gets all the calls that were made to GetPrice.
// Check the length with:
//     len(mockedBTCRepository.GetPriceCalls())
func (mock *MockBTCRepository) GetPriceCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockGetPrice.RLock()
	calls = mock.calls.GetPrice
	mock.lockGetPrice.RUnlock()
	return calls
}

// SetPrice calls SetPriceFunc.
func (mock *MockBTCRepository) SetPrice(price bitcoinentity.BTCPrice) error {
	if mock.SetPriceFunc == nil {
		panic("MockBTCRepository.SetPriceFunc: method is nil but BTCRepository.SetPrice was just called")
	}
	callInfo := struct {
		Price bitcoinentity.BTCPrice
	}{
		Price: price,
	}
	mock.lockSetPrice.Lock()
	mock.calls.SetPrice = append(mock.calls.SetPrice, callInfo)
	mock.lockSetPrice.Unlock()
	return mock.SetPriceFunc(price)
}

// SetPriceCalls gets all the calls that were made to SetPrice.
// Check the length with:
//     len(mockedBTCRepository.SetPriceCalls())
func (mock *MockBTCRepository) SetPriceCalls() []struct {
	Price bitcoinentity.BTCPrice
} {
	var calls []struct {
		Price bitcoinentity.BTCPrice
	}
	mock.lockSetPrice.RLock()
	calls = mock.calls.SetPrice
	mock.lockSetPrice.RUnlock()
	return calls
}
