// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package tests

import (
	"github.com/F0rzend/simple-go-webserver/app/aggregate/user/entity"
	"sync"
)

// Ensure, that MockUserRepository does implement entity.UserRepository.
// If this is not the case, regenerate this file with moq.
var _ entity.UserRepository = &MockUserRepository{}

// MockUserRepository is a mock implementation of entity.UserRepository.
//
// 	func TestSomethingThatUsesUserRepository(t *testing.T) {
//
// 		// make and configure a mocked entity.UserRepository
// 		mockedUserRepository := &MockUserRepository{
// 			CreateFunc: func(user *entity.User) error {
// 				panic("mock out the Create method")
// 			},
// 			DeleteFunc: func(id uint64) error {
// 				panic("mock out the Delete method")
// 			},
// 			GetFunc: func(id uint64) (*entity.User, error) {
// 				panic("mock out the Get method")
// 			},
// 			UpdateFunc: func(id uint64, updFunc func(*entity.User) (*entity.User, error)) error {
// 				panic("mock out the Update method")
// 			},
// 		}
//
// 		// use mockedUserRepository in code that requires entity.UserRepository
// 		// and then make assertions.
//
// 	}
type MockUserRepository struct {
	// CreateFunc mocks the Create method.
	CreateFunc func(user *entity.User) error

	// DeleteFunc mocks the Delete method.
	DeleteFunc func(id uint64) error

	// GetFunc mocks the Get method.
	GetFunc func(id uint64) (*entity.User, error)

	// UpdateFunc mocks the Update method.
	UpdateFunc func(id uint64, updFunc func(*entity.User) (*entity.User, error)) error

	// calls tracks calls to the methods.
	calls struct {
		// Create holds details about calls to the Create method.
		Create []struct {
			// User is the user argument value.
			User *entity.User
		}
		// Delete holds details about calls to the Delete method.
		Delete []struct {
			// ID is the id argument value.
			ID uint64
		}
		// Get holds details about calls to the Get method.
		Get []struct {
			// ID is the id argument value.
			ID uint64
		}
		// Update holds details about calls to the Update method.
		Update []struct {
			// ID is the id argument value.
			ID uint64
			// UpdFunc is the updFunc argument value.
			UpdFunc func(*entity.User) (*entity.User, error)
		}
	}
	lockCreate sync.RWMutex
	lockDelete sync.RWMutex
	lockGet    sync.RWMutex
	lockUpdate sync.RWMutex
}

// Create calls CreateFunc.
func (mock *MockUserRepository) Create(user *entity.User) error {
	if mock.CreateFunc == nil {
		panic("MockUserRepository.CreateFunc: method is nil but UserRepository.Create was just called")
	}
	callInfo := struct {
		User *entity.User
	}{
		User: user,
	}
	mock.lockCreate.Lock()
	mock.calls.Create = append(mock.calls.Create, callInfo)
	mock.lockCreate.Unlock()
	return mock.CreateFunc(user)
}

// CreateCalls gets all the calls that were made to Create.
// Check the length with:
//     len(mockedUserRepository.CreateCalls())
func (mock *MockUserRepository) CreateCalls() []struct {
	User *entity.User
} {
	var calls []struct {
		User *entity.User
	}
	mock.lockCreate.RLock()
	calls = mock.calls.Create
	mock.lockCreate.RUnlock()
	return calls
}

// Delete calls DeleteFunc.
func (mock *MockUserRepository) Delete(id uint64) error {
	if mock.DeleteFunc == nil {
		panic("MockUserRepository.DeleteFunc: method is nil but UserRepository.Delete was just called")
	}
	callInfo := struct {
		ID uint64
	}{
		ID: id,
	}
	mock.lockDelete.Lock()
	mock.calls.Delete = append(mock.calls.Delete, callInfo)
	mock.lockDelete.Unlock()
	return mock.DeleteFunc(id)
}

// DeleteCalls gets all the calls that were made to Delete.
// Check the length with:
//     len(mockedUserRepository.DeleteCalls())
func (mock *MockUserRepository) DeleteCalls() []struct {
	ID uint64
} {
	var calls []struct {
		ID uint64
	}
	mock.lockDelete.RLock()
	calls = mock.calls.Delete
	mock.lockDelete.RUnlock()
	return calls
}

// Get calls GetFunc.
func (mock *MockUserRepository) Get(id uint64) (*entity.User, error) {
	if mock.GetFunc == nil {
		panic("MockUserRepository.GetFunc: method is nil but UserRepository.Get was just called")
	}
	callInfo := struct {
		ID uint64
	}{
		ID: id,
	}
	mock.lockGet.Lock()
	mock.calls.Get = append(mock.calls.Get, callInfo)
	mock.lockGet.Unlock()
	return mock.GetFunc(id)
}

// GetCalls gets all the calls that were made to Get.
// Check the length with:
//     len(mockedUserRepository.GetCalls())
func (mock *MockUserRepository) GetCalls() []struct {
	ID uint64
} {
	var calls []struct {
		ID uint64
	}
	mock.lockGet.RLock()
	calls = mock.calls.Get
	mock.lockGet.RUnlock()
	return calls
}

// Update calls UpdateFunc.
func (mock *MockUserRepository) Update(id uint64, updFunc func(*entity.User) (*entity.User, error)) error {
	if mock.UpdateFunc == nil {
		panic("MockUserRepository.UpdateFunc: method is nil but UserRepository.Update was just called")
	}
	callInfo := struct {
		ID      uint64
		UpdFunc func(*entity.User) (*entity.User, error)
	}{
		ID:      id,
		UpdFunc: updFunc,
	}
	mock.lockUpdate.Lock()
	mock.calls.Update = append(mock.calls.Update, callInfo)
	mock.lockUpdate.Unlock()
	return mock.UpdateFunc(id, updFunc)
}

// UpdateCalls gets all the calls that were made to Update.
// Check the length with:
//     len(mockedUserRepository.UpdateCalls())
func (mock *MockUserRepository) UpdateCalls() []struct {
	ID      uint64
	UpdFunc func(*entity.User) (*entity.User, error)
} {
	var calls []struct {
		ID      uint64
		UpdFunc func(*entity.User) (*entity.User, error)
	}
	mock.lockUpdate.RLock()
	calls = mock.calls.Update
	mock.lockUpdate.RUnlock()
	return calls
}
